### PR TITLE
Make GitHub detect *.spf as Forth.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Same thing...

### CODE REVIEW

**Comment by VoidVolker** [comment]
Strange, even without linguist overrides, github detects this files as forth.

**Comment by larsbrinkhoff** [comment]
There is one `.f` file which GitHub detects as Forth.  This made the entire repository classified as Forth.

**Comment by VoidVolker** [comment]
O, thanks for pointing to this file. I'll fix it.

**Comment by larsbrinkhoff** [comment]
Can I ask a favour?  I'm trying to reach @whiteTigr about this pull request: https://github.com/whiteTigr/A-whole-new-ball-game/pull/1.

Do you know him?

**Comment by VoidVolker** [comment]
Yes, I know him ) I sended him a message via forum, but I don't know if he read it fast.

**Comment by larsbrinkhoff** [comment]
Great, thanks!

**Pull request merged**
